# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas_correctas', models.IntegerField(default=0)),
                ('respuestas_incorrectas', models.IntegerField(default=0)),
                ('nick', models.TextField()),
            ],
        ),
    ]
