# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='tema',
            field=models.TextField(default='Sin tema'),
        ),
    ]
