# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizz_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.TextField(default='SinTema')),
            ],
        ),
        migrations.AlterField(
            model_name='quizz',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Topic'),
        ),
    ]
